name: CI
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
  workflow_dispatch: 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v2
      
      - name: Scripts
        run: |
          docker build -t app .
          echo ${{ secrets.Docker_User}} | docker login -u ${{ secrets.Docker_Password }} --stdin-password
          docker tag app rommel1212/apirest
          docker push rommel1212/apirest
